### ISSUE TITLE
Data source for model

### ISSUE THREAD

**Issue by vollas** [nmis-group/digf-coref#4]
Currently the data source is on server `sodden` under `astamoulakotos` home directory - need to upload this dataset to Pure so we can use `wget` to pull from strath cloud server instead.

**Comment by jeffenhuang** [comment]
Solved by uploading data to Pure https://pure.strath.ac.uk/admin/editor/dk/atira/pure/modules/datasets/external/model/dataset/editor/dataseteditor.xhtml?id=134862926
